on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: code-server

jobs:
  build-container-image:
    env:
      DOCKER_PLATFORM: linux/arm64
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repo
        uses: actions/checkout@v2
     
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.PACKAGES_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./code-server/
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/code-server:arm64-latest
          labels: latest
